require("settings")
require("options")
require("plugins")
require("sessions")
require("terminal")
require("vcs")
require("format")
require("linter")
require("statusline")
require("tabline")
require("explorer")
require("symbols")
require("fuzzer")
require("mappings")

----------------------------------------------------------------------------- EXPERIMENTAL
